export const categories = [
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "fashion", label: "Fashion & Clothing" },
  { value: "home-garden", label: "Home & Garden" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "health", label: "Health & Wellness" },
  { value: "sports", label: "Sports & Outdoors" },
  { value: "automotive", label: "Automotive" },
  { value: "books", label: "Books & Stationery" },
  { value: "toys", label: "Toys & Games" },
  { value: "baby", label: "Baby & Kids" },
  { value: "groceries", label: "Groceries" },
  { value: "pet-supplies", label: "Pet Supplies" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "furniture", label: "Furniture" },
  { value: "kitchen", label: "Kitchen & Dining" },
  { value: "office", label: "Office Supplies" },
  { value: "music", label: "Musical Instruments" },
  { value: "gaming", label: "Gaming" },
  { value: "mobile", label: "Mobile Phones & Accessories" },
  { value: "computers", label: "Computers & Laptops" },
  { value: "cameras", label: "Cameras & Photography" },
  { value: "smart-home", label: "Smart Home Devices" },
  { value: "appliances", label: "Home Appliances" },
  { value: "travel", label: "Travel & Luggage" },
  { value: "watches", label: "Watches" },
  { value: "footwear", label: "Footwear" },
  { value: "bags", label: "Bags & Luggage" },
  { value: "art-crafts", label: "Arts & Crafts" },
  { value: "industrial", label: "Industrial & Scientific" },
  { value: "digital-products", label: "Digital Products" },
];
