export const shopCategories = [
  { value: "fashion", label: "Clothing & Apparel" },
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "health", label: "Health & Wellness" },
  { value: "home", label: "Home & Living" },
  { value: "furniture", label: "Furniture" },
  { value: "groceries", label: "Groceries & Essentials" },
  { value: "books", label: "Books & Stationery" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "toys", label: "Toys & Games" },
  { value: "automotive", label: "Automotive" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "footwear", label: "Footwear" },
  { value: "bags", label: "Bags & Luggage" },
  { value: "watches", label: "Watches" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "baby_products", label: "Baby Products" },
  { value: "kitchen", label: "Kitchen & Dining" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "office", label: "Office Supplies" },
  { value: "art_crafts", label: "Arts & Crafts" },
  { value: "music", label: "Musical Instruments" },
  { value: "gaming", label: "Gaming & Accessories" },
  { value: "mobile", label: "Mobile Phones & Accessories" },
  { value: "computers", label: "Computers & Accessories" },
  { value: "appliances", label: "Home Appliances" },
  { value: "food_beverages", label: "Food & Beverages" },
  { value: "handmade", label: "Handmade Products" },
  { value: "luxury", label: "Luxury Goods" },
  { value: "digital", label: "Digital Products" },
  { value: "services", label: "Services" },
  { value: "other", label: "Other" },
];
