//Path: apps/admin-ui/src/app/layout.tsx
import "./global.css";
import { Nunito, Inter } from "next/font/google";
import Providers from "./provider";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["700", "800"],
  variable: "--font-heading",
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-body",
});

export const metadata = {
  title: "Welcome to admin-ui",
  description: "Generated by create-nx-workspace",
  icons: {
    icon: "/image.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${nunito.variable} ${inter.variable}`}>
      <body className="font-body bg-[#FAF8F3] text-[#292524]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
